spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: parking_db
    liquibase-schema: parking_db

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  application:
    name: Parking System

  batch:
    jdbc:
      initialize-schema: always

input:
  file: ./input/parking_data.csv

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: false