CREATE TABLE parking_records
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    car_number VARCHAR(255)                            NOT NULL,
    car_type   VARCHAR(255)                            NOT NULL,
    entry_time TIMESTAMP WITHOUT TIME ZONE,
    exit_time  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_parking_records PRIMARY KEY (id)
);